# Generated by Django 5.2.7 on 2025-11-04 16:28

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('product_type', models.CharField(choices=[('planner', 'Планинг'), ('sticker', 'Стикер'), ('kit', 'Набор'), ('accessory', 'Аксессуар')], max_length=20, verbose_name='Тип товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
